version: '3'

services:
  jenkins:
    image: jenkins/jenkins
    container_name: jenkinscompose
    ports:
      - 8880:8080
      - 50000:50000
    volumes:
      - ../volumes/jenkins:/var/jenkins_home
    networks:
      - docker-network    


  ubuntu_slave:
    build: 
      context: ../dockerfiles/slave
    command: 
      java -jar agent.jar -jnlpUrl http://192.168.44.44:8880/computer/Slave/jenkins-agent.jnlp -secret cff3219285a9928349e0155486ab8ffe657ad45c6b816c71f5275a5ca628d936 -workDir "/home/"
    container_name: ubuntucompose
    # Allow jenkins build and see containers on the slave.
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - docker-network
    depends_on: 
      - jenkins
  

  selenium_hub:
    image: selenium/hub
    container_name: selenium-hubcompose
    ports:
      - 4444:4444
    networks:
      - docker-network
  

  selenium_firefox:
    image: selenium/node-firefox
    container_name: firefoxcompose
    environment:
      - HUB_HOST=selenium-hubcompose
      - HUB_PORT=4444
    depends_on: 
      - selenium_hub
    networks:
      - docker-network
  

  artifactory:
    image: docker.bintray.io/jfrog/artifactory-oss:latest
    container_name: artifactorycompose
    volumes:
      - ../volumes/artifactory:/var/opt/jfrog/artifactory
    ports:
      - 8081:8081
      - 8082:8082
    networks:
      - docker-network


networks:
  docker-network:
    driver: bridge