---
federation:
  inbound:
    service-id-mapping:
    - from: "jfrou@*"
      to: "jfrou@01fm73sv6s4d6cyy1rm4qbwzj4"
    - from: "jfevt@*"
      to: "jfevt@01fm73sqysjgst0t1vddpw09kv"
    - from: "jfob@*"
      to: "jfob@01fm73sqysjgst0t1vddpw09kv"
    - from: "jfmd@*"
      to: "jfmd@01fm73sw2hffqpz18jr6kq7m9p"
    - from: "jfrt@*"
      to: "jfrt@01fm73t3m1gsbw1sp9a3en1jrf"
    - from: "jffe@*"
      to: "jffe@000"
licenses:
- server-name: "17cf92a2bffd"
  key: "cHJvZHVjdHM6CiAgYXJ0aWZhY3Rvcnk6CiAgICBwcm9kdWN0OiBaWGh3YVhKbGN6b2dNakF5TVMw\r\
    \neE1pMHhNVlF4TVRvd016b3pORm9LYVdRNklHWmpNRGc0WkdJMExUVmtNVEV0TkdObE9DMDRaVE0y\r\
    \nTFRBd1lqZGtOREF6TkdGaU9RcHZkMjVsY2pvZ2NHRjJhWGczTXprME5RcHdjbTl3WlhKMGFXVnpP\r\
    \nZ29nSUhKbFoybHpkSEpoZEdsdmJrdGxlVlJ2YTJWdU9pQmxlVW95V2xoSmFVOXBTWGxKYVhkcFpF\r\
    \naHNkMGxxYjJsVGJHUlZTV2wzYVZsWGVHNUphbTlwVld4TmVVNVVXV2xNUTBweVlWZFJhVTlwU25w\r\
    \nTmFscFNUbFJvZFUxWWNEVmxhbU14VTBaQ1NsbHJWakJqYTBwVlRGZE9UbE5ITlZKVGFscEZaRVph\r\
    \nY1ZRelVqTmxWVGx2WlZoUmQwbHVNQzVsZVVwc1pVaFJhVTlwU2pkWVEwcDVXbGRrY0dNelVubFpX\r\
    \nRkp3WWpJMVZXSXlkR3hpYkZJMVkwZFdZMGxxY0dOSmJFSkdWV3N4UWxSclZrOVdSbmRwVEVaM2FX\r\
    \nTnRWbTVoV0U0d1kyMUdNR0ZYT1hWVE1sWTFXRU5KTmxoRFNUTk5WRVpyV1ZkSmVGbDVNRFZOYWtK\r\
    \ncFRGUlJlVnBIVVhSUFJHaHNUbWt3TVZsdFJUVk5Na2w0VG5wYWFFMXFWbU5KYmpCcFRFTktlbVJY\r\
    \nU1dsUGFVa3pUVlJHYTFsWFNYaFplVEExVFdwQ2FVeFVVWGxhUjFGMFQwUm9iRTVwTURGWmJVVTFU\r\
    \nVEpKZUU1NldtaE5hbFZwVEVOS2Vsa3pRV2xQYVVwNVdsZGtjR016VW14amFVbHpTVzFHTVZwRFNU\r\
    \nWkpiWEJ0V1cwNVFVdHBTWE5KYld4NlkzbEpOa2x0Y0hkWldHeEJXVzFLYlU0eVJUQlpWRUYwVFdw\r\
    \nbmVrNXBNREJPVjFFMFRGUm5lRTFxU1hST2VtUnNUbGRSTVZreVNtcE5WRTV0U1dsM2FWcFlhSGRK\r\
    \nYW04d1RucHJkMDFxU1RST2FrVXdURU5LY0ZsWVVXbFBha1V5VFhwWk1rMXFaekpOVkZGelNXMXdN\r\
    \nR0ZUU1RaSmFrWnNUWHBCTWxsVVFUUk1WMGt3VFhwUmRFNUVXbWxPVXpBMFRrZEpNa3hVYkdoWlZG\r\
    \ncHRXbGRGZVU5WFZYaE9VMG81TG1GU2VWSkljVVkyVVhSRVJVRjNRV015TFVSTmFtUnpNMUJ0V1hN\r\
    \nMFVtOXFhRGgyZVZWUlZrWm5jbTB0U25CM1h6VlhUM2hqZEZWaldXMWpURk5LTlhsVlJqZE1hRGRp\r\
    \nWDJ4V2VFNDNWMWhJZEd4V1RGZG5jMUJRYVRkdGJuSmZZbXBYZDBsMVlYWmtVakJWTVVaZlJYZGtW\r\
    \nMUl4ZVV4aWRHOHRWRjlPYlhndGIzQk9UbU5hY25sMFFtWjJSM3AxUlVSUFdsSjJTM1oyYm5kR1NG\r\
    \nVjRaWFU0ZDJ3NFpXc3RNVWxhZVZKSVNXTlBjRzk2YjNRMVZESTBWWFoyUnkxclZsVlVVMFpEWm5V\r\
    \ndFdtbHBNVkpLTkY5Tk4yVlBRVmx1ZWsxMWRFUk9TMWxOVFdSdFJHZFZWMU52TkU4NFNWUnZhRlp0\r\
    \nTm14VldFOHdZM2RYZGxWUWJGZERWVTlqVlhsSE5HazBUM0ZJVGtOZkxXUm9NRTlUYURneFZUWXdT\r\
    \nekZzWmxWS1VIRmZiVUpQZUVWM2VIZFlPVEJsYzNacVl6QXhVa1J3U2w5dWEyaDViVlphZEMxWFZE\r\
    \nQjNjbTkxTkdsRFFrTkpVMHhEZHdwemFXZHVZWFIxY21VNklHNTFiR3dLZEhKcFlXdzZJSFJ5ZFdV\r\
    \nS2RIbHdaVG9nVkZKSlFVd0tkbUZzYVdSR2NtOXRPaUF5TURJeExURXhMVEV4VkRFeE9qQXpPak0w\r\
    \nTGprME5Gb0sKICAgIHNpZ25hdHVyZTogZjZnanBXL2FLSnAyVGd5SndpbnNtUGJBTUxIQllSKytk\r\
    \nUmU2M1lZa0M0UnBLWFFSdjVGNER2YktUYUhZSXV1RDF3Y1NaY05VYzhVZ3BjRTFBTUZuWVU0bVZO\r\
    \nRHhWbGJFamFGbDFFVEIxS0t5bVlYQTRJckFGU0l6a1l6Ri9EeVJ5M05Jajl5R1hReDRNTW9VQ0tl\r\
    \neG16Tm1GVjgvU01rYkNydTBBTGlxTkFEekxqQVBEMXo5U3BiZEZ2YWhsYWhZTGJhVnRNZUlRb3du\r\
    \nRVRHREJsVGZMd1Y5QWJWd3E5RFhiWUdsMWc3Vk4wWE5vdi92TzdTTFVOUWxyRkdMa2ZHNVFSUGl0\r\
    \nbmZuelNMT0JoY3QzOFl3YUtMc0JuRnJ6L1BCdjBxUFB2ekdtWXRsUGhlOVBtK0ZOcW83Qzg4REZ3\r\
    \nbGt3ODE3WHRSMUlBZUZQMXR6MWh1M3FnPT0KdmVyc2lvbjogMQo=\r\n"
schema-version: 2
